# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Tue, 20 Jul 2021 08:04:32 +0000
*               @ALL          1
*               @user         8
