<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Tue, 20 Jul 2021 11:07:37 +0000
 */

$conf['title'] = 'KNUCSE Wiki';
$conf['lang'] = 'ko';
$conf['template'] = 'sprintdoc';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
