<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: root
 * Date: Wed, 21 Jul 2021 07:31:58 +0000
 */

$conf['title'] = 'KNU CSE WiKi';
$conf['lang'] = 'ko';
$conf['template'] = 'white';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['defer_js'] = 0;
