# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Wed, 21 Jul 2021 07:27:54 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root:$2y$10$ZpwGuWco2DSJ9jq3MOgRXOasxaALN4wdJHH6bskElTQYTfDsdX3S.:곽승규:tmdrb0912@naver.com:admin,user
