# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Tue, 20 Jul 2021 08:04:32 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

root:$2y$10$X6RUNZAE3WiBZmcfKAGuNuqHAHYu//7FmrEVQd8efaGh9JuaOT1X2:이주형:juhyoung98@knu.ac.kr:admin,user
test:$2y$10$6pxNoRaZQRzVUdcIfm7Jq.oyU/wruQxk4uWzxLhWYv/f65Ladk82e:테스트:juhyoung98@knu.ac.kr:user
